hpge_string:
  "1":
    radius_in_mm: 218
    angle_in_deg: 60
    minishroud_radius_in_mm: 51.0
    rod_radius_in_mm: 46.5
  "2":
    radius_in_mm: 222
    angle_in_deg: 94.29
    minishroud_radius_in_mm: 48.0
    rod_radius_in_mm: 43.5
  "3":
    radius_in_mm: 222
    angle_in_deg: 120
    minishroud_radius_in_mm: 44.0
    rod_radius_in_mm: 39.5
  "4":
    radius_in_mm: 222
    angle_in_deg: 145.71
    minishroud_radius_in_mm: 48.0
    rod_radius_in_mm: 43.5
  "5":
    radius_in_mm: 218
    angle_in_deg: 180
    minishroud_radius_in_mm: 54.0
    minishroud_delta_length_in_mm: -200
    rod_radius_in_mm: 49.5
  "6":
    radius_in_mm: 218
    angle_in_deg: 210
    minishroud_radius_in_mm: 51.0
    rod_radius_in_mm: 46.5
  "7":
    radius_in_mm: 218
    angle_in_deg: 240
    minishroud_radius_in_mm: 51.0
    rod_radius_in_mm: 46.5
  "8":
    radius_in_mm: 222
    angle_in_deg: 274.29
    minishroud_radius_in_mm: 48.0
    minishroud_delta_length_in_mm: -300
    rod_radius_in_mm: 43.5
  "9":
    radius_in_mm: 222
    angle_in_deg: 300
    minishroud_radius_in_mm: 44.0
    rod_radius_in_mm: 39.5
  "10":
    radius_in_mm: 222
    angle_in_deg: 325.71
    minishroud_radius_in_mm: 48.0
    rod_radius_in_mm: 43.5
  "11":
    radius_in_mm: 218
    angle_in_deg: 0
    minishroud_radius_in_mm: 54.0
    rod_radius_in_mm: 49.5
  "12":
    radius_in_mm: 218
    angle_in_deg: 30
    minishroud_radius_in_mm: 51.0
    rod_radius_in_mm: 46.5
hpges:
  B00032C:
    rodlength_in_mm: 53.5
    baseplate: medium
  V07302A:
    rodlength_in_mm: 103.5
    baseplate: medium
  V00050A:
    rodlength_in_mm: 103.5
    baseplate: medium
  V05267A:
    rodlength_in_mm: 103.5
    baseplate: medium
  V00048A:
    rodlength_in_mm: 103.5
    baseplate: medium
  V00048B:
    rodlength_in_mm: 103.5
    baseplate: medium
  V01240A:
    rodlength_in_mm: 103.5
    baseplate: medium
  V03421A:
    rodlength_in_mm: 103.5
    baseplate: xlarge
  V03422A:
    rodlength_in_mm: 131.0
    baseplate: xlarge
  V10447B:
    rodlength_in_mm: 126.5
    baseplate: xlarge
  V11924A:
    rodlength_in_mm: 126.5
    baseplate: xlarge
  V08682A:
    rodlength_in_mm: 122.0
    baseplate: xlarge
  V09724A:
    rodlength_in_mm: 103.5
    baseplate: xlarge
  V02160A:
    rodlength_in_mm: 103.5
    baseplate: large
  V02162B:
    rodlength_in_mm: 112.0
    baseplate: large
  V05612A:
    rodlength_in_mm: 103.5
    baseplate: large
  V07647A:
    rodlength_in_mm: 103.5
    baseplate: large
  V07647B:
    rodlength_in_mm: 103.5
    baseplate: large
  V07302B:
    rodlength_in_mm: 78.0
    baseplate: large
  V05266B:
    rodlength_in_mm: 103.5
    baseplate: large
  B00000C:
    rodlength_in_mm: 53.5
    baseplate: medium
  B00061B:
    rodlength_in_mm: 53.5
    baseplate: medium
  B00076C:
    rodlength_in_mm: 53.5
    baseplate: medium
  B00079B:
    rodlength_in_mm: 53.5
    baseplate: medium
  B00079C:
    rodlength_in_mm: 53.5
    baseplate: medium
  V01404A:
    rodlength_in_mm: 103.5
    baseplate: medium
  B00000D:
    rodlength_in_mm: 53.5
    baseplate: medium
  B00002C:
    rodlength_in_mm: 53.5
    baseplate: medium
  B00035A:
    rodlength_in_mm: 53.5
    baseplate: medium
  B00035B:
    rodlength_in_mm: 53.5
    baseplate: medium
  V00050B:
    rodlength_in_mm: 103.5
    baseplate: medium
  V04549A:
    rodlength_in_mm: 103.5
    baseplate: medium
  V07298B:
    rodlength_in_mm: 103.5
    baseplate: medium
  V06643A:
    rodlength_in_mm: 122.0
    baseplate: medium
  V08682B:
    rodlength_in_mm: 77.0
    baseplate: xlarge
  V10784A:
    rodlength_in_mm: 126.5
    baseplate: xlarge
  V11925A:
    rodlength_in_mm: 126.5
    baseplate: xlarge
  V11947B:
    rodlength_in_mm: 122.0
    baseplate: xlarge
  V09372A:
    rodlength_in_mm: 131.0
    baseplate: xlarge
  V09374A:
    rodlength_in_mm: 103.5
    baseplate: xlarge
  V02160B:
    rodlength_in_mm: 77.0
    baseplate: large
  V04199A:
    rodlength_in_mm: 122.0
    baseplate: large
  V04545A:
    rodlength_in_mm: 122.0
    baseplate: large
  V05267B:
    rodlength_in_mm: 122.0
    baseplate: large
  V07646A:
    rodlength_in_mm: 122.0
    baseplate: large
  V06659A:
    rodlength_in_mm: 122.0
    baseplate: large
#  the length is just a rough guess from MaGe, the radius is from slides of A.
#  Lubashevskiy. all positions from CAD model.
calibration:
  "1":
    radius_in_mm: 155
    angle_in_deg: 158.57
    tube_radius_in_mm: 19
    length_in_mm: 1400
  "2":
    radius_in_mm: 155
    angle_in_deg: 261.43
    tube_radius_in_mm: 19
    length_in_mm: 1400
  "3":
    radius_in_mm: 155
    angle_in_deg: 338.57
    tube_radius_in_mm: 19
    length_in_mm: 1400
  "4":
    radius_in_mm: 155
    angle_in_deg: 81.43
    tube_radius_in_mm: 19
    length_in_mm: 1400
